Bump a few Maven plugins.
I'm not sure that any of these end up being _necessary_ to what I'm doing in https://github.com/google/guava/issues/7331#issuecomment-2248105640 / https://github.com/google/guava/issues/3990#issuecomment-1444307178. But the upgrade to `maven-surefire-plugin` changes that plugin's toolchain behavior, so I particularly want to use the new version there in advance of starting to use toolchains.

This includes a workaround for a bug in the JDK 8 javac. (I don't know why the bug is appearing only after these upgrades.)

```
Error:  /home/runner/work/guava/guava/guava/src/com/google/common/hash/BloomFilter.java:[78,29] error: cannot find symbol
  symbol:   class Serializable
  location: class BloomFilter<T>
  where T is a type-variable:
    T declared in class BloomFilter
```
RELNOTES=n/a
PiperOrigin-RevId: 655637260