Attempt to hack around JDiff error:
Error: duplicate comment id: com.google.common.base.Preconditions.checkArgument_changed(boolean, String, Object)

JDiff is using `Object` instead of `Object...` for the varargs method,
producing a conflict with the overload that _actually_ accepts `Object`.