Use `assertThrows` almost wherever we can.
(prompted by discussion on cl/559765949)

Ideally, I'd use it everywhere except under GWT. For simplicity, I've touched only files _without_ a top-level `@GwtCompatible` annotation, even though I could also touch `@GwtIncompatible` sections of `@GwtCompatible` files. Future Work.

I had to revert a couple changes in `TypeTokenTest` because they triggered what appears to be a bug in Java 8's reflection implementation. (Alternatively, I could have configured the tests to be skipped under Java 8.)

```
java.lang.AssertionError: expected java.lang.IllegalStateException to be thrown, but nothing was thrown
	...
	at com.google.common.reflect.TypeTokenTest.testVariableTypeTokenNotAllowed(TypeTokenTest.java:69)
	...
```

```
java.lang.AssertionError: unexpected exception type thrown; expected:<java.lang.IllegalArgumentException> but was:<java.lang.NullPointerException>
	...
	at com.google.common.reflect.TypeTokenTest.testGetSubtype_fromTypeVariable(TypeTokenTest.java:1245)
	...
Caused by: java.lang.NullPointerException
	...
	at com.google.common.reflect.TypeToken.<init>(TypeToken.java:165)
	at com.google.common.reflect.TypeToken.<init>(TypeToken.java:102)
	at com.google.common.reflect.TypeToken$SimpleTypeToken.<init>(TypeToken.java:1310)
	at com.google.common.reflect.TypeToken.of(TypeToken.java:175)
	at com.google.common.reflect.TypeTokenTest.lambda$testGetSubtype_fromTypeVariable$4(TypeTokenTest.java:1247)
	...
```

PiperOrigin-RevId: 563137030